version: '3'

services:
  rootnode:
    image: golang
    build: .
    networks:
      - chord-network
    ports:
      - 8080
    tty: true
  node:
    image: golang
    build: .
    networks:
      - chord-network
    ports:
      - 8081
    depends_on:
      - rootnode
    tty: true

networks:
  chord-network:
